"""empty message

Revision ID: 0bf4cf269cf0
Revises: c72a76869f1f
Create Date: 2025-09-27 20:23:21.278273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bf4cf269cf0'
down_revision: Union[str, Sequence[str], None] = 'c72a76869f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### end Alembic commands ###
