"""empty message

Revision ID: 8b5220a33286
Revises: 13cc98bc98a3
Create Date: 2025-09-27 21:12:58.799762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b5220a33286'
down_revision: Union[str, Sequence[str], None] = '13cc98bc98a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferred_username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('given_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('family_name', sa.String(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('users', 'family_name')
    op.drop_column('users', 'given_name')
    op.drop_column('users', 'preferred_username')
    op.drop_column('users', 'name')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'email')

    # ### end Alembic commands ###
