"""empty message

Revision ID: ebbccbfb0baf
Revises: 351554ea8800
Create Date: 2025-09-27 20:50:19.102708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebbccbfb0baf'
down_revision: Union[str, Sequence[str], None] = '351554ea8800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    
    # ### end Alembic commands ###
