"""empty message

Revision ID: bead26eb72f7
Revises: 3b33ebff181d
Create Date: 2025-10-01 15:08:15.894008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bead26eb72f7'
down_revision: Union[str, None] = '3b33ebff181d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'region')
    # ### end Alembic commands ###
